name: Deploy Ilmenauer Open 2024

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get Latest Hugo Version
        id: hugo_version
        run: |
          latest_version=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')

          minimum_version=0.124.0

          if [ "$(printf '%s\n' "$minimum_version" "$latest_version" | sort -V | head -n1)" = "$minimum_version" ]; then
            echo "Using latest version: $latest_version"
          else
            echo "Using minimum version: $minimum_version"
            latest_version=$minimum_version
          fi

          echo "Hugo version to install: $latest_version"
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Install Hugo Extended
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${{ env.latest_version }}/hugo_extended_${{ env.latest_version }}_Linux-64bit.tar.gz
          tar -xzf hugo_extended_${{ env.latest_version }}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Build Hugo site
        run: hugo

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:   
          path: './public' # Upload the public directory generated by Hugo

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Clean up
        run: |
          git clean -fX
