name: Build Hugo Site

on:
 pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hugo Extended
        run: |
          HUGO_VERSION=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Build Hugo Site
        run: hugo
